### ISSUE TITLE
多次连接服务器报错Throwing OutOfMemoryError "Could not allocate JNI Env

### ISSUE THREAD

**Issue by wangchengyan** [goAV/NettyAndroid#1]
当服务器停止，或者把网络关掉的话，反复调用reset2Connect();方法，会报错
ashmem_create_region failed for 'indirect ref table': Too many open files
Throwing OutOfMemoryError "Could not allocate JNI Env

**Comment by AnMokoto** [comment]
U could build with a fixed pool or list to get restart count .Must call the method `Recycle` in `onDestroy` and this project was used at work at that time and you could modify it according to your work 😄
